name: Setup NVGT
description: Sets up the NVGT scripting language.
inputs:
  latest:
    description: Set if it is latest to use
    required: false
    default: true
  version:
    description: The NVGT tagged version to install
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Download and install NVGT
      uses: robinraju/release-downloader@v1
      with:
        latest: ${{ inputs.latest }}
        fileName: "${{ runner.os }}.zip"
        tag: ${{ inputs.tag }}
        repository: harrymkt/nvgtreleases

    - name: Extract NVGT
      shell: bash
      run: |
        unzip "${{ github.workspace }}/${{ runner.os }}.zip" -d "${{ github.workspace }}/nvgtgameengine"
        echo "${{ github.workspace }}/nvgtgameengine" >> $GITHUB_PATH
    - name: Checkout NVGT version
      shell: bash
      run: |
        nvgt --v