name: Setup NVGT
description: Download and install NVGT for the current platform.

inputs:
  version:
    required: false
    default: ""
  latest:
    required: false
    default: "true"
  dev:
    required: false
    default: "false"
  add-to-path:
    required: false
    default: "true"

outputs:
  path:
    description: Path to NVGT install

runs:
  using: node24
  main: dist/index.js