name: Setup NVGT
description: Sets up the NVGT scripting language.
inputs:
  latest:
    description: Set if it is latest to use
    required: false
    default: true
  version:
    description: The NVGT tagged version to install if not latest
    required: false
    default: ""
  official:
    description: Official release
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Set Options
      id: options
      shell: bash
      run: |
        if [[ "${{ inputs.official }}" == "true" ]]; then
          echo "repo=nvgtreleases" >> $GITHUB_OUTPUT
        else
          echo "repo=nvgtreleases_u" >> $GITHUB_OUTPUT
        fi
    - name: Download
      uses: robinraju/release-downloader@v1
      with:
        latest: ${{ inputs.latest }}
        fileName: "${{ runner.os }}.zip"
        tag: ${{ inputs.tag }}
        repository: harrymkt/${{ steps.options.outputs.repo }}

    - name: Extract NVGT
      shell: bash
      run: |
        unzip "${{ github.workspace }}/${{ runner.os }}.zip" -d "${{ github.workspace }}/nvgtgameengine"
        echo "${{ github.workspace }}/nvgtgameengine" >> $GITHUB_PATH
        cd "${{ github.workspace }}/nvgtgameengine"
        chmod +x nvgt
    - name: Checkout NVGT version
      shell: bash
      run: |
        nvgt --v