name: Test action
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Setup NVGT
        id: engine
        uses: harrymkt/setup-nvgt@main
        with:
          dev: true
          tools: nvgtpm
      - name: Checkout NVGT Outputs
        shell: bash
        run: |
          nvgt -V
          ls "${{ steps.engine.outputs.path }}"
