name: Test Action
on:
  push:
    branches: [main]
    paths: ["dist/index.js"]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Setup NVGT
        id: engine
        uses: ./
        with:
          dev: true
          tools: nvgtpm@dev
      - name: Checkout NVGT Outputs
        shell: bash
        run: |
          nvgt -V
          nvgtpm program about
          ls "${{ steps.engine.outputs.path }}"
